[package]
name = "clap_loading_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["clap_derive", "derive", "env"] }
kankyo = "0.3.0"
